# Introduction

This hackbook will enable you to stop using pornography immediately, painlessly, and permanently without willpower or any sense of deprivation or sacrifice. It won't place any judgement, embarrassment, or pressure to undergo painful measures.

In fact, there's absolutely no need to cut down or reduce your usage whilst reading; doing so is actually detrimental.

Perhaps this goes against everything you've been told, but ask yourself if what you've been told has worked? If it had, you wouldn't be reading this hackbook.

Pornography addiction manifests in various ways with far-reaching societal effects. Many people use pornography because the internet allows instantaneous access to *supernormal stimuli*. Consider if the following questions apply to you.

-   Do you spend far more time viewing porn than you originally intended?

-   Are you unsuccessful in efforts to stop or limit your consumption of pornography?

-   Has time spent viewing pornography interfered with, or taken precedence over personal or professional commitments, hobbies, or relationships in your life?

-   Do you go out of your way to keep your pornography consumption secret (e.g. deleting browser history, lying about viewing porn)?

-   Has viewing pornography caused significant problems in intimate relationship(s)?

-   Do you experience a cycle of arousal and enjoyment before and during pornography consumption, followed by feelings of shame, guilt, and remorse after?

-   Do you spend significant amounts of time thinking about pornography, even when not watching it?

-   Has viewing pornography caused any other negative consequences in your personal or professional life (e.g. missed work, poor performance, neglected relationships, financial problems)?

If you’re a porn user that depends on it for masturbation or sex, all you need to do is read on.  
If you’re here for a loved one, all you need to do is persuade them to read this book.  
If unable to persuade them, read the book yourself. Understanding the method assists getting the message across and preventing your children from starting. Don't be fooled by the fact that they don't have access to it now – all do before getting hooked.

## Warning {-}

Perhaps you are somewhat apprehensive about reading this book. Perhaps, like many porn users, the mere thought of stopping fills you with panic and although you have every intention of stopping one day, it is not today.

If you’re expecting this book to ’scare’ you into quitting with the various health issues users risk, such as sexual dysfunction (including porn induced erectile dysfunction), unreliable arousal, loss of interest in real sex partners, brain hypofrontality, and the blinding accusation that it's a filthy, disgusting habit and *you* are a stupid, spineless, weak-willed jellyfish, you’ll be sorely disappointed. Those tactics never helped me to quit and if they were going to help you, you'd have quit already.

Conventional methods of quitting advocate using willpower, or substitution methods such as porn diets (using once every X days) and cutting down consumption, which are equally ineffective because they don't actually remove the reasons for using porn. Ultimately, turning something into a forbidden fruit isn't how you treat addiction.

Many sites go into detail about effects on the brain, backed up by peer-reviewed research about neurotransmitters and neuroplasticity. While these sites are informative, many are aware of the dangers of porn, yet choose to do nothing. Users young and old tend to avoid such material regardless, feeling safe in the knowledge that one look at a porn site won't kill them.

This method, referred to as EasyPeasy, works differently. Some of the things about to be said might be difficult to believe, but by the time you've finished this book, you’ll not only believe them, you’ll wonder how you could have ever been brainwashed into believing otherwise.

There's a common misconception that we choose to watch porn. Porn addicts (yes, addicts) no more choose to watch porn than alcoholics choose to become alcoholics, than heroin addicts choose to become heroin addicts. It's true we choose to boot up the laptop or smartphone, fire up the browser, and visit our favorite ’online harem’. I occasionally choose to go to the cinema, but I certainly didn't choose to spend my whole life in the cinema theatre. Originally, curiosity and human nature took me there, but I wouldn't have started had I known I'd become addicted, causing the decline of my health, happiness, and relationships. *"If only I'd heard about sexual dysfunction on my first visit to that porn site!"*

Take a moment to reflect, did you ever make the ’positive’ decision that you must/need porn to masturbate? Or that you should/must/need porn-induced fantasies to spice up sex with your partner? Or, that at certain times in your life, you couldn't enjoy a good night's sleep or perhaps even pass an evening after a hard day at work without surfing for porn? Or that you couldn't concentrate or handle stress without it? At what stage did you decide that you *needed* porn, that you *needed* it permanently in your life, feeling insecure, even panic-stricken without porn, without your online harem?

Like every other user, you have been lured into the most sinister and subtle trap that man and nature have ever combined to devise. There's not a person alive, whether a user themselves or not, that likes the thought of their children using porn to cope or for pleasure. This means that all addicts wish they had never started. That's unsurprising: no one needs porn to enjoy life or cope with stress before they get hooked.

At the same time, all users wish to continue to use. After all, nobody forces us to launch our browser's Incognito mode. Whether they understand the reason or not, it's only users that decide to knock on the doors of their online harems.

If there were a magic button the user could press to wake up the following morning as if they'd never accessed their first tube site, the only addicts tomorrow would be young people still ’experimenting’.

The only thing that prevents us from quitting is **FEAR!** Fear caused by the belief that we’ll have to survive an indeterminate period of misery, deprivation, and unsatisfied craving in order to be free from porn. These spawn from irrational beliefs, both learned and acquired, such as:

-   Masturbation or sex leading to orgasm is the *only* and *most* important thing in life.

-   Porn is ’safer’ than real-life sex because porn can't reject me.

-   Porn is educative and useful.

-   Entitlement to a ’superior’ sex experience.

-   More is always better.

These irrational beliefs spawn irrational consequences when acted upon, including:

-   Worshipping and obsessing when a ’perfect 10/10’ is found.

-   Perceiving yourself as a loser if you miss out on sex, as if it's the most important thing in the human experience.

-   Holding out for a perfect 10.

-   Being excessively judgmental and critical of prospective partners.

-   Forcing yourself to have sex whether you want it or not.

It's fear that a night all by yourself will be miserable, spent fighting uncontrollable impulses. Fear that the night before exams will be a night from hell without porn. Fear that we’ll never be able to concentrate, handle stress, or be as confident without our little crutch and that our personality and character will change.

But most of all, fear that ’once an addict, always an addict’: that we’ll never be completely free, spending the rest of our lives craving the occasional porn-induced orgasm at odd times. If, as I did, you've already tried all the conventional ways to quit and been through the misery and torture of the ’willpower method’, you’ll not only be affected by that fear, you’ll be convinced you can never quit.

If you’re apprehensive, panic-stricken, or feel that the time is not right for you to quit, let me assure you that your apprehension and panic isn't relieved by porn -- it's caused by it. You didn't decide to fall into the porn trap, but like all traps, it's designed to ensure you remain trapped. Ask yourself, when you viewed those first porn pictures and videos, did you decide to come back to view them as long as you live? So when will you quit? Tomorrow? Next year? Stop kidding yourself! The trap is designed to hold you for life. Why else do you think all these other addicts don't quit before it ’kills’ their lives?

I've referred to a magic button; EasyPeasy works just like that magic button. Let me make it quite clear, EasyPeasy isn't magic, but for me and others who've found it so easy and enjoyable to quit, it seems like it!

The warning is as follows:  
This is a chicken and egg situation: every addict wants to quit and every addict can find it easy and enjoyable to quit. It's only **fear** that prevents users from attempting to quit. The single greatest gain is to be rid of that fear, but you won't be free of that fear until you complete the book. On the contrary, your fear may increase as you continue reading, which might prevent you from finishing it. Take this comment from one woman.

**"I've just finished reading EasyPeasy. I know that it's only been four days, but I feel so great, I know that I’ll never need to PMO again. I first started to read your book five months ago, got half way through and panicked. I knew that if I went on reading I would have to stop. Wasn't I silly?"**

You didn't decide to fall into the trap, but be clear in your mind: you won't escape from it unless you make the affirmative decision to do so. You may already be straining at the leash to quit, or you may be apprehensive about the very thought, but either way, please bear in mind: **YOU HAVE NOTHING TO LOSE!**

If at the end of the book you decide that you wish to continue to use porn for masturbation or sex, there's nothing to prevent you from doing so. You don't even have to cut down or stop using porn while reading the book, and remember, there is no shock treatment. On the contrary, I have only good news for you. Can you imagine how Andy Dufresne felt when he finally escaped from Shawshank Prison? That's how I felt when I escaped from the porn trap, and that's how the ex-users who've used EasyPeasy feel. By the end of the book, that's how you’ll feel! Go for it!

## Finally... {-}

Everyone can find it easy and enjoyable to quit porn, including you! All you have to do is read the rest of this book with an open mind; the more you understand, the easier it will be. Even if you don't understand a word, provided you follow instructions, you’ll find it easy. Most importantly, you won't go through life moping for porn or feeling deprived, and by the end of the book the only mystery will be why you did it for so long.

With EasyPeasy, there are only two reasons for failure.

**Failure to carry out instructions.**
Some will find it annoying that book is so dogmatic about certain recommendations, such as not to try cutting down or using substitutes. I certainly don't deny that there are many who have succeeded in stopping using such ruses, but they've succeeded in *spite of* and not because of them. Some people can make love standing on a hammock, but it isn't the easiest way. The numbers for opening this trap's lock are in this book, but they need to be used in the correct order: going from one chapter to the next and not skipping chapters.

**Failure to understand.**
Don't take anything for granted, question not only what you’re told, but your own views and what society has told you about sex, internet porn, and addiction. For example, those to believe it's just a habit, ask yourself why other habits, some of which are enjoyable, are easy to break, while a habit that feels awful, costs energy, time and virility is so difficult to.Those that believe you enjoy porn, ask yourself why other things that are infinitely more enjoyable you can take or leave. Why do you *have* to have porn, panic setting in if you don't?

EasyPeasy is about to give you the knowledge on how easy and enjoyable it is to quit porn. Like many others, one of my greatest triumphs in life has been escaping the porn trap. There's no need to feel depressed, on the contrary, you’re about to accomplish something that every user on the planet would love to achieve: **FREEDOM!**

**REMEMBER, DO NOT SKIP CHAPTERS.**

Some terms before you begin:  
***PMO***: The cycle of porn, masturbation, and orgasm.  
***Online harem***: Websites hosting high-speed internet porn.
