# The Easy Method

This book's objective is directing you into a new frame of mind. In contrast to the usual method of stopping - whereby you start off the feeling of climbing Mount Everest and spend the next few weeks craving and feeling deprived - you start right away with a feeling of elation, as if cured of a terrible disease. From then on, the further you go through life, the more you will look at this period of time and wonder how you ever used any porn in the first place. You will look at other porn users with pity, as opposed to envy.

Provided that you're not someone who had never become addicted (reading for your significant other) or had quit (or is in the fasting days of a "porn diet"), it's essential to keep using until you have finished the book completely. This may appear to be a contradiction, and this instruction to continue masturbating to porn causes more objection than any other, but as you read further your desire to use porn will gradually be reduced. **Take this instruction seriously: Attempting to quit early will not benefit you.**

Many don't finish the book because they feel they have to give something up, some even deliberately only reading one line per day in order to postpone the evil event. Look at it this way, what have you got to lose? If you don't stop at the end of the book, you’re no worse off than you are now. It's by definition a Pascal's Wager, a bet taken where you have nothing to lose and high chances of large gains.

Incidentally, if you haven't watched porn for a few days or weeks, but aren't sure whether you’re a porn user, ex-user, or a non-user, then don't use porn to masturbate whilst reading. In fact, you’re already a non-user, but we have to let your brain catch up with your body. By the end of the book, you’ll be a happy non-user. EasyPeasy is the complete opposite of the normal method, where one lists the considerable disadvantages of porn and says:  
*"If only I can go long enough without porn, eventually the desire will go and I can enjoy life again, free of slavery."*  
This is the logical way to go about it, with thousands stopping every day using this method. However, it's very difficult to succeed for the following reasons:

**Stopping PMO isn’t the real problem.**
Every time you finish your session, you've stopped using it. You may have powerful reasons on the first day of your once-in-four porn diet to say *“I don’t want to use porn, or even masturbate any more.”* All users do, and their reasons are more powerful than you can possibly imagine. The real problem is day two, ten, or ten-thousand where in a weak moment you’ll have ‘just one peek’, want another, and suddenly you’re an addict again.

**Awareness of the health risks generates more fear, making it more difficult to stop.**
Tell a user it's destroying their virility and the first thing they’ll do is reach for something to surge their dopamine: a cigarette, alcohol, or even firing up the browser to search for porn.

**All reasons for stopping actually make it harder.**
This is due to two reasons. First, we’re continually being forced to give up our ’little friend’ or some prop, vice, or pleasure (whichever way the user perceives it). Second, they create a "blind". We do not masturbate for the reasons we should stop. The real question is, why do we want or need to do it?

With EasyPeasy, we (initially) forget the reasons we'd like to stop, face the porn problem and ask ourselves the following questions:

1.  What is porn doing for me?

2.  Am I actually enjoying it?

3.  Do I really need to go through life sabotaging my mind and body?

The beautiful truth is that *all porn* does absolutely nothing for you whatsoever. Let me make it quite clear, it's not that the disadvantages of being a user outweigh the advantages, it's that there are ***zero*** advantages to looking at internet porn.

Most users find it necessary to rationalise why they use porn, but the reasons they come up with are all fallacies and illusions.

First, we'll remove these fallacies and illusions. In fact, you'll soon realise there is nothing to give up. Not only that, but there are marvellous, positive gains from being a non-PMOer, with well-being and happiness only two of these gains. Once illusions that life will never be quite as enjoyable without porn is removed - realising that not only is life just as enjoyable without it but infinitely more so - and once feelings of being deprived or missing out are eradicated, we'll go back to reconsider increased well-being and happiness—and the dozens of other reasons for quitting porn. These realisations will become positive additional aids to help you achieve what you really desire: enjoying your life free from the slavery of porn addiction!

## The Sinister Trap

Internet porn is the most subtle, sinister trap that man and nature have combined to devise; it's the only trap in nature whose setup doesn't require hard work. Some of us are even warned about the dangers, but we can't believe how they aren't enjoying it. But what gets us into it in the first place? Typically, free samples from amateurs and professionals who share. That's how the trap is sprung, your first ’peek’ has stains and holes with most thumbnails on any porn page being amateurish and home-made clips of unknown models. If the first timer's gaze was filled only with angelic beauties and professional models then alarm bells would ring.

Due to this mismatch in clips, our young minds are reassured we’ll never become hooked, thinking because we don't enjoy them, we can stop whenever we want to. As intelligent human beings, we'd then understand why half the adult population was systematically addicted to something cutting down their very potential to perform what they’re viewing. Curiosity brings us closer to their doorsteps, but not daring to click on some thumbnails, fearing they'd make you ill. If you accidentally clicked on one, your only desire being getting away from the page as soon as possible.

We then spend the rest of our lives trying to understand why we do it, telling children not to start, and at odd times trying to escape ourselves. The trap is designed such that we try and stop only due to an ’incident’, whether sexual performance, loss of a career or relationship, shortage of drive or just plain feeling like a leper. As soon as we stop, we have more stress due to withdrawal pangs with the method we relied on to remove that stress unavailable.

After a few days of torture we come to the decision that we've picked the wrong time to quit, deciding we’ll wait for periods without stress, which upon arriving removes our reason for initially stopping. Of course, that period will never arrive as we internally believe our lives tend to become more and more stressful. Leaving the protection of our parents, stresses such as jobs, homemaking, mortgages, babies, bigger houses and more babies crowd our lives. This is an illusion, the truth being that the most stressful parts of any creature's life are early childhood and adolescence.

We tend to confuse responsibility and stress. A user's life -- like a drug addict's -- automatically becomes more stressful because porn doesn't relax you or relieve stress, as some try to make you believe. It's just the reverse, causing you to become more stressed as you continue using, piling more straw onto the camel's back. Even users who kick the habit (most do one or more times throughout their lives) can lead perfectly happy lives yet suddenly become hooked again. Wandering into the pornographic maze, our minds become hazy and we spend the rest of our lives trying to escape. Many do succeed, only to fall into the sinister trap at a later date.

Porn addiction is a complex and fascinating puzzle, and much like a Rubik's Cube, practically impossible to solve. But if you have the solution, it's simple and fun! EasyPeasy contains the solution to this puzzle, leading you out of the maze, never wandering in again. All you have to do is follow the instructions. However, if you take a wrong turn, the rest of the instructions are pointless.

Anyone can find it easy to stop, we must first establish facts. No, not facts designed to scare you, there's already more than enough information out there. If that was going to stop you, you'd have already stopped. But why do we find it difficult to stop? Answering this requires us to know the real reason we’re still using porn, boiling down to two factors. They are:

-   Nature and internet porn.

-   Brainwashing.

Porn users are intelligent, rational human beings. They know they’re taking enormous future risks so they spend lots of time rationalising their ’habit’. But porn users in their hearts know they’re fools, knowing they had no need to use porn before becoming hooked. Most remember that their first ’peek’ was a mix of revulsion and novel curiosity. They then specialise in locating, filtering and bookmarking sites, working hard to become hooked.

Most annoyingly, there's the sense that non-addicts - most women, older guys and people living in countries where high-speed internet porn is unavailable - aren't missing out on anything and find the situation laughable. By dismantling these factors in the next chapters, you too will understand the sinister trap!
