# Why is it difficult to stop?

All users feel something evil has possessed them. In the early days, it's a simple question of *"I will stop, just not today"*, but eventually we progress to believing we haven't got enough willpower to stop or that there's something inherent in porn we must have in order to enjoy life. Porn addiction can be compared to clawing your way out of a slippery pit: as you near the top, you see the sunshine - but find yourself sliding back down as your mood dips. Eventually you open your browser, and as you masturbate, you feel awful and try to work out why you have to do it.

Ask a user, *"If you could go back to the time before you became hooked, with the knowledge you have now, would you have started using porn?"*

*"NO WAY!"* would be the reply.

Ask the confirmed user, someone who defends internet porn and doesn't believe it causes injury to the brain or downregulation of dopamine receptors: *"Do you encourage your children to use porn?"*

*"NO WAY!"* is again the reply.

Porn is an extraordinary enigma. As said previously, the problem isn't explaining why it's easy to stop, it's explaining why it's difficult. The real problem is explaining why anyone does it *after* getting insights on neurological damage. Part of the reason we start is because of the tens of millions already into it, yet all of those wish they hadn't started in the first place and tell us it's like living life in second gear. We cannot quite believe they are not enjoying it. We associate it with freedom or being ’sex-educated’ and work hard to become hooked ourselves. We then spend the rest of our lives telling others not to do it and trying to kick the habit ourselves.

We also spend a significant proportion of our time feeling hopeless and miserable. ’Educating’ ourselves with the supernormal makes us prefer and long for these cold images, even when warm, real ones are available! Through the constant surge and fall of dopamine induced by PMO, we sentence ourselves to a lifetime of irritability, anger, stress, fatigue, and sexual dysfunction. Using porn, with its absence of the best parts of sex and connection, we end up feeling miserable and guilty.

In fact, reading about internet pornography's addictive and destructive capabilities here and on other sites makes us more nervous and hopeless! What sort of hobby is it that when you’re doing it, you wish you weren't, and when you aren't, you crave it? Users despise themselves every time they read about hypofrontality and desensitisation, every time they use behind their trusting partner's back, every time they can't bring themselves to exercise after a daytime session. An otherwise intelligent and rational human being spends all their days in contempt. But worst of all, what do users get from having to endure life with these awful black shadows at the back of their mind? **Absolutely nothing!**

You might be thinking *"That’s all very well, I know this, but once you’re hooked on these things it’s very difficult to stop."* But why is it so difficult? Some say it's because of the powerful withdrawal symptoms, but as you’ll come to learn, the actual withdrawal symptoms are so mild that you should be aware of PMOers who have lived and died without realising they’re drug addicts.

Some say internet porn is free and hence humankind should claim this biological bonanza, but this is untrue—it's addictive and acts just like any drug. Ask a user that swears they only enjoy ’erotica’ like Playboy magazines if they've ever crossed the line to ’unsafe porn’ and if completely honest, they'd the times they'd unwittingly rationalized doing so, rather than not use anything at all.

Enjoyment has nothing to do with it either: I enjoy crayfish, but I never got to the point where I had to have crayfish every day. With other things in life, we enjoy them while we’re doing them, but we don't sit around feeling deprived when we’re not.

Some say:  
*"It’s educational!"* So when is your graduation?  
*"It’s sexual satisfaction!"* So why do it alone instead of finding a partner and saving it for them?  
*"It’s a feeling of release!"* Release from the stresses of real life? Porn won't remove the source of the stress, but it does add to it.

Many believe that porn relieves boredom, which is also a fallacy. Boredom is a frame of mind. Porn will habituate you to novelty-seeking in no time, causing you to become increasingly bored until you finally participate in that wild-goose chase for just the right clip, causing you to become increasingly wired to seek anything that evokes novelty, strong emotion, and eventually, outrageous shock value.

Some say they only do it because their friends and everyone they know do it. If so, pray that your friends don't start cutting their heads off to cure a headache! Most users who think about it come to conclude that it's just a habit. This is not really an explanation, but having discounted all the usual, rational explanations, it appears to be the only remaining excuse. Unfortunately, it's equally illogical. Every day of our lives we change habits, some of them very enjoyable. We've been brainwashed to believe that PMO is a habit and that habits are difficult to break.

Are habits difficult to break? Drivers in the US are in the habit of driving on the right hand side of the road, yet when travelling overseas they break the habit with hardly any aggravation whatsoever. It is clearly a fallacy that habits are hard to break. We make and break habits every day of our lives. So why do we find it difficult to break a habit that makes us feel deprived when we don't have it, guilty when we do, one that we would love to break anyway, when all we have to do is *stop doing it?*

The answer is that porn isn't habit, **it’s addiction!** That's why it appears to be so difficult to ’give up’. Most users don't understand addiction and believe that they get some genuine pleasure or crutch from porn. They believe they’re making a genuine sacrifice if they quit.

The beautiful truth is that once you understand the true nature of porn addiction and the reasons why you use it, you’ll stop doing it, just like that. Within three weeks, the only mystery will be why you found it necessary to use porn as long as you have and why you can't persuade other users *how nice it is to not be a PMOer!*
